export const TERMS = {
  fr: {
    title: "Conditions Générales de Vente (CGV)",
    subtitle: "Canary Foil Club — Costa Adeje, Ténérife",
    sections: [
      { h: "1. Champ d'application et objet", p: ["Les présentes Conditions Générales de Vente (CGV) régissent toutes les prestations de services proposées par le Canary Foil Club (ci-après « le Prestataire »), spécialisé dans l'initiation et l'excursion encadrée en surf électrique hydrofoil (Fliteboard), ainsi que l'organisation d'événements B2B (Corporate Sunset), à Costa Adeje, Ténérife, Espagne. Le fait de réserver une session implique l'adhésion entière et sans réserve du client aux présentes CGV."] },
      { h: "2. Réservation et Paiement", p: ["Modalités : Les réservations s'effectuent en ligne via le site internet officiel ou par l'intermédiaire de partenaires agréés (conciergeries hôtelières).", "Paiement : Le règlement est exigé dans sa totalité au moment de la réservation via la passerelle de paiement sécurisée en ligne. Aucune réservation n'est considérée comme valide sans encaissement préalable (ce qui permet de lutter contre les no-shows).", "Taxes : Tous nos prix sont affichés en Euros (€) et incluent l'IGIC (Impuesto General Indirecto Canario) au taux en vigueur."] },
      { h: "3. Conditions de Participation et Sécurité", p: ["Âge et condition physique : Les participants doivent être âgés d'un minimum de 16 ans (une autorisation parentale écrite est obligatoire pour les mineurs). Chaque participant doit savoir nager 50 mètres et être en bonne condition physique.", "Consignes de sécurité : Le port du gilet de sauvetage (fourni) est strictement obligatoire pendant toute la durée de la session. Le client s'engage à respecter scrupuleusement les instructions de l'instructeur muni de la liaison radio.", "Tolérance Zéro : Le Prestataire se réserve le droit d'annuler, sans aucun remboursement, la session d'un participant présentant des signes manifestes d'ivresse, de consommation de substances illicites ou refusant de porter les équipements de sécurité."] },
      { h: "4. Politique d'Annulation et Météo", p: ["Annulation par le client : Plus de 48 heures avant la session : remboursement intégral. Entre 48 h et 24 h avant la session : avoir valable sur une prochaine session ou report selon disponibilités. Moins de 24 heures avant ou absence le jour J : aucun remboursement ne sera accordé.", "Annulation pour cause météorologique (Force Majeure) : La sécurité étant notre priorité absolue, le Prestataire est seul juge des conditions de navigation (houle excessive, vent trop fort, tempête). En cas d'annulation de la part du Prestataire pour raisons météorologiques ou de sécurité, la session sera reportée à une date ultérieure ou intégralement remboursée."] },
      { h: "5. Responsabilité et Dommages Matériels", p: ["Le matériel mis à disposition (Fliteboards, batteries, casques radio BB Talkin) reste l'entière propriété du Canary Foil Club. Aucune location libre n'étant autorisée, les sessions se déroulent toujours sous la supervision directe d'un instructeur diplômé.", "Toutefois, en cas de non-respect volontaire et manifeste des consignes de sécurité de l'instructeur entraînant une casse anormale ou une détérioration volontaire du matériel, le client pourra être tenu responsable des frais de réparation."] },
      { h: "6. Option Drone et Propriété Visuelle", p: ["L'option « Pack Drone 4K » est soumise à des créneaux spécifiques (les lundis, mardis et mercredis).", "Les images et vidéos capturées sont destinées à un usage strictement personnel et privé pour le client. Le Canary Foil Club se réserve le droit d'utiliser les contenus visuels à des fins promotionnelles (réseaux sociaux, site web), sauf opposition expresse formulée par le client avant le début de la session."] },
      { h: "7. Données Personnelles (RGPD)", p: ["Les informations recueillies lors de la réservation sont nécessaires pour la gestion des dossiers clients et le traitement des paiements. Conformément à la réglementation européenne (RGPD) et à la loi espagnole sur la protection des données (LOPD), le client dispose d'un droit d'accès, de rectification et de suppression de ses données en contactant directement le support du Canary Foil Club."] },
      { h: "8. Litiges et Droit Applicable", p: ["Les présentes CGV sont soumises au droit espagnol.", "En cas de litige, une solution amiable sera recherchée en priorité. À défaut, les tribunaux compétents de Santa Cruz de Tenerife seront seuls compétents, sous réserve des dispositions impératives du droit de la consommation applicables."] },
    ],
  },
  en: {
    title: "Terms and Conditions of Sale",
    subtitle: "Canary Foil Club — Costa Adeje, Tenerife",
    sections: [
      { h: "1. Scope and purpose", p: ["These Terms and Conditions of Sale govern all services offered by Canary Foil Club (hereinafter “the Provider”), specialised in supervised electric hydrofoil surfing (Fliteboard) lessons and excursions, as well as B2B events (Corporate Sunset), in Costa Adeje, Tenerife, Spain. Booking a session implies the client's full and unreserved acceptance of these Terms."] },
      { h: "2. Booking and Payment", p: ["Booking: Bookings are made online through the official website or via approved partners (hotel concierges).", "Payment: Full payment is required at the time of booking through the secure online payment gateway. No booking is considered valid without prior payment (which helps prevent no-shows).", "Taxes: All prices are displayed in Euros (€) and include IGIC (Impuesto General Indirecto Canario) at the applicable rate."] },
      { h: "3. Participation Requirements and Safety", p: ["Age and fitness: Participants must be at least 16 years old (written parental consent is mandatory for minors). Each participant must be able to swim 50 metres and be in good physical condition.", "Safety rules: Wearing the (provided) life vest is strictly mandatory throughout the session. The client undertakes to strictly follow the instructions of the radio-equipped instructor.", "Zero tolerance: The Provider reserves the right to cancel, without any refund, the session of any participant showing obvious signs of intoxication, use of illicit substances, or refusing to wear the safety equipment."] },
      { h: "4. Cancellation and Weather Policy", p: ["Cancellation by the client: More than 48 hours before the session: full refund. Between 48 h and 24 h before the session: credit valid for a future session or rescheduling subject to availability. Less than 24 hours before or no-show on the day: no refund will be granted.", "Cancellation due to weather (Force Majeure): Safety being our absolute priority, the Provider is the sole judge of sailing conditions (excessive swell, strong wind, storm). If the Provider cancels for weather or safety reasons, the session will be rescheduled or fully refunded."] },
      { h: "5. Liability and Equipment Damage", p: ["The equipment provided (Fliteboards, batteries, BB Talkin radio helmets) remains the sole property of Canary Foil Club. As no unsupervised rental is permitted, sessions always take place under the direct supervision of a certified instructor.", "However, in the event of deliberate and manifest disregard of the instructor's safety instructions resulting in abnormal breakage or intentional damage to the equipment, the client may be held liable for repair costs."] },
      { h: "6. Drone Option and Image Rights", p: ["The “4K Drone Pack” option is subject to specific time slots (Mondays, Tuesdays and Wednesdays).", "Captured photos and videos are intended strictly for the client's personal and private use. Canary Foil Club reserves the right to use visual content for promotional purposes (social media, website), unless the client expressly objects before the start of the session."] },
      { h: "7. Personal Data (GDPR)", p: ["Information collected at booking is necessary for managing client files and processing payments. In accordance with European regulation (GDPR) and Spanish data protection law (LOPD), the client has the right to access, rectify and delete their data by contacting Canary Foil Club support directly."] },
      { h: "8. Disputes and Governing Law", p: ["These Terms are governed by Spanish law.", "In the event of a dispute, an amicable solution will be sought first. Failing that, the competent courts of Santa Cruz de Tenerife shall have exclusive jurisdiction, subject to mandatory consumer protection provisions."] },
    ],
  },
  es: {
    title: "Condiciones Generales de Venta",
    subtitle: "Canary Foil Club — Costa Adeje, Tenerife",
    sections: [
      { h: "1. Ámbito de aplicación y objeto", p: ["Las presentes Condiciones Generales de Venta regulan todos los servicios ofrecidos por Canary Foil Club (en adelante «el Prestador»), especializado en la iniciación y excursiones guiadas de surf eléctrico hydrofoil (Fliteboard), así como en la organización de eventos B2B (Corporate Sunset), en Costa Adeje, Tenerife, España. Reservar una sesión implica la aceptación plena y sin reservas de estas condiciones por parte del cliente."] },
      { h: "2. Reserva y Pago", p: ["Modalidades: Las reservas se realizan en línea a través de la web oficial o mediante partners autorizados (conserjerías de hotel).", "Pago: El pago se exige en su totalidad en el momento de la reserva a través de la pasarela de pago segura en línea. Ninguna reserva se considera válida sin el cobro previo (lo que permite evitar las ausencias).", "Impuestos: Todos los precios se muestran en euros (€) e incluyen el IGIC (Impuesto General Indirecto Canario) al tipo vigente."] },
      { h: "3. Condiciones de Participación y Seguridad", p: ["Edad y condición física: Los participantes deben tener un mínimo de 16 años (autorización parental escrita obligatoria para menores). Cada participante debe saber nadar 50 metros y estar en buena forma física.", "Normas de seguridad: El uso del chaleco salvavidas (incluido) es estrictamente obligatorio durante toda la sesión. El cliente se compromete a respetar escrupulosamente las instrucciones del instructor equipado con radio.", "Tolerancia cero: El Prestador se reserva el derecho de cancelar, sin reembolso alguno, la sesión de un participante con signos evidentes de embriaguez, consumo de sustancias ilícitas o que se niegue a llevar el equipo de seguridad."] },
      { h: "4. Política de Cancelación y Meteorología", p: ["Cancelación por el cliente: Más de 48 horas antes de la sesión: reembolso íntegro. Entre 48 h y 24 h antes: bono válido para una próxima sesión o cambio de fecha según disponibilidad. Menos de 24 horas antes o ausencia el día de la sesión: no se concederá ningún reembolso.", "Cancelación por meteorología (Fuerza Mayor): Siendo la seguridad nuestra prioridad absoluta, el Prestador es el único juez de las condiciones de navegación (oleaje excesivo, viento fuerte, tormenta). En caso de cancelación por parte del Prestador por motivos meteorológicos o de seguridad, la sesión se aplazará o se reembolsará íntegramente."] },
      { h: "5. Responsabilidad y Daños Materiales", p: ["El material puesto a disposición (Fliteboards, baterías, cascos con radio BB Talkin) sigue siendo propiedad exclusiva de Canary Foil Club. Al no permitirse el alquiler libre, las sesiones se desarrollan siempre bajo la supervisión directa de un instructor titulado.", "No obstante, en caso de incumplimiento voluntario y manifiesto de las instrucciones de seguridad del instructor que provoque una rotura anormal o un deterioro intencionado del material, el cliente podrá ser responsable de los gastos de reparación."] },
      { h: "6. Opción Drone y Derechos de Imagen", p: ["La opción «Pack Drone 4K» está sujeta a horarios específicos (lunes, martes y miércoles).", "Las imágenes y vídeos captados están destinados a un uso estrictamente personal y privado del cliente. Canary Foil Club se reserva el derecho de utilizar los contenidos visuales con fines promocionales (redes sociales, web), salvo oposición expresa del cliente antes del inicio de la sesión."] },
      { h: "7. Datos Personales (RGPD)", p: ["La información recogida en la reserva es necesaria para la gestión de los expedientes de clientes y el tratamiento de los pagos. Conforme al reglamento europeo (RGPD) y a la ley española de protección de datos (LOPD), el cliente dispone de derecho de acceso, rectificación y supresión de sus datos contactando directamente con el soporte de Canary Foil Club."] },
      { h: "8. Litigios y Legislación Aplicable", p: ["Las presentes condiciones se rigen por el derecho español.", "En caso de litigio, se buscará prioritariamente una solución amistosa. En su defecto, los tribunales competentes de Santa Cruz de Tenerife serán los únicos competentes, sin perjuicio de las disposiciones imperativas del derecho de consumo aplicables."] },
    ],
  },
};
